name: Docker CI for Docker Hub Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  docker_build_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Deploy to local server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                echo nodejs
